bind 127.0.0.1 -::1
protected-mode yes
port 6379
tcp-keepalive 300
timeout 0
daemonize no
supervised no
logfile ""
dir /data
appendonly yes
appendfsync everysec
save 3600 1
save 300 100
save 60 10000
dbfilename dump.rdb
